### ISSUE TITLE
issue with transform-object-assign import

### ISSUE THREAD

**Issue by designbystephen** [tannerlinsley/react-form#113]
**Version:** 1.3.0

**Stack:**

> ERROR in ./~/react-form/lib/index.js
> Module build failed: ReferenceError: Unknown plugin "transform-object-assign" ...

**Code:**
The only place I am using it on my component is as an import
`import { Form, Text } from 'react-form';`

I didn't have any luck finding any open issues that point to this. Judging from the documentation this is not a required dependency I need to include in my own babelrc or package.json and it should just work out of the box.  

Any help is appreciated.

**Comment by thg303** [comment]
@designbystephen it might be an issue with your build system. I think you have to tell it to ignore **node_modules** directory.

**Comment by designbystephen** [comment]
That was the issue.

Added to my babel-loader rule in webpack:
`exclude: /node_modules/`

Thanks for your help.
