### ISSUE TITLE
issue with rendering components which start with lowercase

### ISSUE THREAD

**Issue by thg303** [tannerlinsley/react-form#15]
here's a sample code:
```
import React, { Component } from 'react';
import { Form } from 'react-form';

const foo = () => {
  return (
    <h1>FOO</h1>
  )
}

const CompanyFormComponent = () => {
  return (
    <form>
      <foo />
    </form>
  )
}

const CompanyForm = Form()(CompanyFormComponent);

export default CompanyForm;
```

it simply does not render the **foo** but when I rename the component to **Foo** everything works fine. 
not a big deal but took me couple of hours to find it

**Comment by tannerlinsley** [comment]
Unfortunately, JSX is limited to some rules that prohibit lowercase component variables from being rendered as components. http://stackoverflow.com/questions/37345230/can-i-use-component-name-in-lower-case-in-jsx
