### ISSUE TITLE
Demo not working in IE

### ISSUE THREAD

**Issue by duplich** [tannerlinsley/react-form#2]
Your Demo app and my local one are not working in Internet Explorer

**Comment by tannerlinsley** [comment]
Could you post any errors you are seeing in the console? More info would help me solve the problem.

**Comment by duplich** [comment]
Hi @tannerlinsley, I did not receive any errors, the site kind of ended up in a loop and never loaded. Did you try to load it with IE?

**Comment by tannerlinsley** [comment]
I'm on a Mac right now. So I haven't tried it yet

**Comment by tannerlinsley** [comment]
Looks like it's just a polyfill issue for IE in general.  I've added the babel-polyfill for the example, but still no dice. I have to admit, it's pretty terrible debugging Internet Explorer.  Add in the virtual machine requirement, and it sucks real bad.  If anyone has any IE debugging experience, I'll allow them to reopen this issue.  For now I have verified that the example works on all *modern* web browsers.

**Comment by duplich** [comment]
I agree that this is terrible, to work with IE but most of the bigger clients still use IE as their main browser. Therefore we can not neglect this issue. :/

**Comment by tannerlinsley** [comment]
I just signed up for browser stack. So I'll take another look at this today

**Comment by mybks** [comment]
Hi @tannerlinsley, great package, but also thinking about the clients who uses IE, is it still an issue?
