### ISSUE TITLE
Trouble setting defaultValues for a form.

### ISSUE THREAD

**Issue by tizzle** [tannerlinsley/react-form#20]
I'm writing a little shop backend using react-form and i'm struggling prefilling the form to edit existing data. I tried passing this to the form component like this

```
<AddEditProductForm
  onSubmit= { this.handleSubmit }
  defaultValues = {{
    name:this.props.item.name,
    color:this.props.item.color,
    …
   }}
/>
```

This adds the defaultValues data to the Forms props object alright, but it doesn't render in the form. What's even more confusing is: When not passing the defaultValues to the form, the props object has an empty defaultValues object. This feels like the approach i used should/could work.

When adding the defaultValues directly inside the form component it works alright, but is not dynamic.

Can anyone help me to get this fixed?
Thanks.

**Comment by tannerlinsley** [comment]
Try just sending in the values instead of the default values:
```
<AddEditProductForm
  onSubmit= { this.handleSubmit }
  values = {{
    name:this.props.item.name,
    color:this.props.item.color,
    …
   }}
/>
```

Does that work?

**Comment by tizzle** [comment]
Like a charm!

Thank you so much for the prompt answer.

**Comment by tannerlinsley** [comment]
Though @tizzle's issue was solved by other means, a bug that spawned this issue was going and fixed that did not allow default values to be set via props.

**Comment by jgentes** [comment]
I'm running into this same problem. If I set the defaultProps with hard-coded values, it works fine. If I use this.props.value it doesn't show the value. I've tried using the `values` workaround but that didn't seem to do it either.
