### ISSUE TITLE
Dynamically updating custom input children

### ISSUE THREAD

**Issue by donovanhiland** [tannerlinsley/react-form#237]
I'm trying to update the children in a select field based on the value of another field in the form, however, it seems that updates to the component are being blocked. If I do the same thing on a select component not wrapped in `FormField` it works as expected.

Example. `SelectField` is a custom input wrapped in `FormField` and wired up. In this case it's wrapped in a component that takes options and a filter which comes from another input in the form. 

    render() {
      return (
        <SelectField field="someField">
          {this.props.options
            .filter(option => option.type === this.props.filterByType)
            .map((option, index) => (
              <option key={option.id} value={option.id}>
                {option.value}
              </option>
            ))}
        </SelectField>
      )
    }

The render method in the wrapper gets hit, and it successfully receives the values from the other input, and filters options successfully. The problem is that that SelectField never re-renders. What am I missing? Any ideas?

**Comment by joepuzzo** [comment]
There is an internal optimization that will only rerender if the forms elements update. the workaround for now is to pass the updated prop to the select Field. We are currently working on V3 and it will not do this optimization by default. Stand by for V3

**Comment by donovanhiland** [comment]
Ok great I'll hang tight. Do you have or could you give an example of the workaround? I don't understand what you mean 😄

**Comment by donovanhiland** [comment]
Oh I see. FormField is comparing all new props except children. So I just need to pass some other non children prop to the select field 👍

**Comment by joepuzzo** [comment]
Yup ^^^^ kind of a hack but im working on fixing this. Also a heads up.. stay clear of nested forms if you can.. i am going to update README soon to say this but that is going to be one of the major breaking changes.

**Comment by joepuzzo** [comment]
Hey this should now work in V3 as we check the other props now!

**Comment by beausmith** [comment]
Howdy! I was having the same issue, but using a custom `Field` component `InputRadioGroup` which renders similar to the built in `RadioGroup`, but uses in Reactstrap `Input` components and markup.

This `InputRadioGroup` component takes a `options` prop which is an array of labels for each radio option. The label for each is a string with values from other form values.

The component was not updating until I added a prop [as suggested above](https://github.com/react-tools/react-form/issues/237#issuecomment-362143348) to force the `Field` to update. The prop I added was the `shouldUpdate`, see code below.

**Question:** Is this the proper way to force a custom `Field` to update in `react-form` v3.3.2?

Using custom component:
```js
// goalEvents is a number,
// goalPeriod is a string.
<InputRadioGroup
  id="goalCheck"
  label="Goal Check"
  defaultValue="none"
  shouldUpdate={goalEvents+goalPeriod} // prop to force update of component
  options={[{
    label: 'None',
    value: 'none',
  }, {
    label: `Equal to ${goalEvents} per ${goalPeriod}`,
    value: '==',
  }, {
    label: `Greater than or equal to ${goalEvents} per ${goalPeriod}`,
    value: '>=',
  }, {
    label: `Less than or equal to ${goalEvents} per ${goalPeriod}`,
    value: '<=',
  }]}
/>
```

Custom component definition using `Field` & `fieldApi`:
```js
// note: className props and other n/a code removed to make this sample simpler…
export const InputRadioGroup = props => (
  <Field
    field={props.id}
    defaultValue={props.defaultValue}
    shouldUpdate={props.shouldUpdate} // When this prop value changes, this component 
    // will shallow-compare props and nextProps and update if any have changed. 
    // Code here: https://github.com/react-tools/react-form/blob/master/src/components/Field.js#L65
  >
    { fieldApi => {
      const { onChange, defaultValue, options, shouldUpdate, id, ...rest } = props
      const { value, setValue, setTouched } = fieldApi
      return (
        <div>
          {_.map(options, option => (
            <Label key={option.value}>
              <ReactstrapInput
                {...rest}
                type={props.type || 'radio'}
                name={props.id}
                value={option.value}
                checked={value === option.value}
                onChange={e => {
                  setValue(e.target.value)
                  if (onChange) {
                    onChange(e.target.value, e)
                  }
                  if (layout === 'buttons') {
                    setTouched()
                  }
                }}
              /> {option.label}
            </Label>
          ))}
        </div>
      )
    }}
  </Field>
)
```
