### ISSUE TITLE
show errors on submit

### ISSUE THREAD

**Issue by mulmulovich** [tannerlinsley/react-form#239]
Hello,

showing errors on submit failure improve the user experience because he dont need to wonder 
what field value is invalid or required

i tried few approaches to achieve this functionality but i couldn't find a way to do it.
am i missing something? can you suggest what is the way to do it?

**Comment by joepuzzo** [comment]
Can you elaborate? Im not sure i understand what feature you are looking for here

**Comment by eruby94** [comment]
This may be suggesting something like adding a has-error class to whichever input has an error. This is certainly achievable without making it natively supported by the library.

@mulmulovich have you tried generating the className for each input based on the formApi errors object? If you have your errors named to match your inputs, then it shouldn't be too hard to accomplish this.

**Comment by joepuzzo** [comment]
V3 now allows you to get the error at the field level.. i would recommend creating your own custom input like in the example here https://react-form.js.org/#/custom-input
