### ISSUE TITLE
New Landing Page Idea

### ISSUE THREAD

**Issue by ryanmunger** [tannerlinsley/react-form#242]
Hey Guys,

Love the library! Here is a quick idea I threw together for a landing page. Thinking maybe this could link out to your existing documentation? If you guys would like, we can continue to iterate on this idea and I can integrate this/open a pull request.

Let me know what you think :)

http://competent-bell-8315b0.bitballoon.com/

**Comment by joepuzzo** [comment]
This looks sick!

**Comment by joepuzzo** [comment]
Hey @ryanmunger looks like the link is dead... how can i get access to that page

**Comment by Mylan34** [comment]
@ryanmunger - Dead

**Comment by theodorDiaconu** [comment]
```ATTENTION
MetaMask believes this domain to have malicious intent and has prevented you from interacting with it.

This is because the site tested positive on the Ethereum Phishing Detector.

You can turn MetaMask off to interact with this site, but it's advised not to.```
