### ISSUE TITLE
Types for typescript

### ISSUE THREAD

**Issue by tomorrow10** [tannerlinsley/react-form#256]
Hi, is there any roadplan, when/if the [types for typescript() ](https://www.npmjs.com/package/@types/react-form) will be aligned to v3.0.x ?

**Comment by joepuzzo** [comment]
Ahhhh No lol. Im a pure JS guy :) if you would like to add, maintain, and test type files i would have no problem with that ( submit a pull request ). But this is not in our roadmap at the moment.

**Comment by ChristoRibeiro** [comment]
if you add flow you can generate the Typescript types definition file with [flowgen](https://github.com/joarwilk/flowgen).

**Comment by FredyC** [comment]
@cameron-mcateer & @TiuSh contributed to current typing. I am wondering, do you guys still use react-form and possibly plan on expanding it? If not, I might take on that task.

@joepuzzo It's a bit problematic that you are not keeping a proper changelog, it will be hard to discover the changes from 2.16.2 up to 3.5.2 and reflect that in typings.

**Comment by cameron-mcateer** [comment]
Same, I no longer use the react-form library. My initial typings were messy anyways so I think it's best someone else keep improving them 🙂

**Comment by szazo** [comment]
Hi, I have started to create typings for v3, but not yet finished so there might be some clumsy solutions in it, but I hope it can be helpful: https://github.com/szazo/react-form-typings

**Comment by FredyC** [comment]
@szazo I am not sure it's worth it since react-form is basically deprecated and being replaced by informed. Sadly that module lacks on typescript field as well.

**Comment by szazo** [comment]
Oh, thanks for the info :) I will check that in my next project, but fortunately, the API looks very similar.

**Comment by FredyC** [comment]
Yea, I like the informed as well, it's more like next gen, keeping mostly similar API, but getting rid of some internal complexities (eg. redux) and general API bloat that got accumulated here over time.
