### ISSUE TITLE
warning for React.PropTypes validation

### ISSUE THREAD

**Issue by sabatsu** [tannerlinsley/react-form#27]
I get this warning using it...
Warning: You are manually calling a React.PropTypes validation function for the `formAPI` prop on `Form`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Does someone can help me with that?

**Comment by tannerlinsley** [comment]
Are you calling the prop type validation yourself?

**Comment by tannerlinsley** [comment]
Closing for now.  If you have more questions, let's continue the discussion in the closed issue.

**Comment by sabatsu** [comment]
No i am not.

**Comment by sabatsu** [comment]
Hey @tannerlinsley ...
could you please help me with that?
I am getting this warning - 
Warning: You are manually calling a React.PropTypes validation function for the `zoom` prop on `ReactCropper`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by tannerlinsley** [comment]
Hi @sabatsu.  React-form doesn't utilize any prop-types anywhere in it's source code, and it's dependencies are also free of its usage as well.  I can't be sure, but it sounds like you are using a component that does.  https://facebook.github.io/react/warnings/dont-call-proptypes.html for more information.

If you could please reproduce the problem in [this webpack-bin](http://www.webpackbin.com/V1AI--xtz), that would extremely helpful in figuring out the solution :)
