### ISSUE TITLE
className prop for RadioGroup

### ISSUE THREAD

**Issue by mjhm** [tannerlinsley/react-form#276]
It would be ever so handy if props from `<RadioGroup ...>` were passed into the `<div ...>` element at https://github.com/react-tools/react-form/blob/master/src/components/form-fields/RadioGroup.js#L26

In particular I'd like to be able to assign a `className` to the `RadioGroup`.

**Comment by joepuzzo** [comment]
Hmm this is a good idea 👍🏼

**Comment by denizdogan** [comment]
According to the 3.0.0 release notes, `RadioGroup` components have been deprecated: https://github.com/react-tools/react-form/releases/tag/3.0.0 Has this been changed?

**Comment by joepuzzo** [comment]
Crap lol i need to update that changelog it has .. Radio Groups were NOT depricated
