### ISSUE TITLE
Call validate manually

### ISSUE THREAD

**Issue by amelierosser** [tannerlinsley/react-form#29]
Hi,

I need the ability to call validate manually. Validation happens both locally and server side. If the server responds with errors I need to show them.

Does the api expose a way to call validate?

**Comment by tannerlinsley** [comment]
Currently, no.  This would be a great addition though, along with some other promise support being discussed in #28.  I'll get to work :)

**Comment by chungnho** [comment]
I did a workaround where in `componentWillReceiveProps`, for each field that had a serverside error, it does `this.props.setValue(field, this.props.getValue(field))` which would trigger the `validate`.

**Comment by tannerlinsley** [comment]
Going to track this with #28
