### ISSUE TITLE
Custom Input: how to detect if the input is being async-validated?

### ISSUE THREAD

**Issue by Romasato** [tannerlinsley/react-form#290]
Is there a way in a custom form control to detect when the field is being asynchronously validated?
Tried executing fieldApi.validatingField(), but it always complains about the validatingField not being a function - though when I check in console it is actually shown as a function. Weird.

My idea is to use the main form's validate() method to return a Promise for some fields if that field needs server-side validation. And then custom field control would know it is still pending validation (showing a spinner icon).

How can that be achieved?

Thanks!

**Comment by joepuzzo** [comment]
I think what your are looking for is `formApi.validating` see the docs here https://react-form.js.org/#/async-validation
