### ISSUE TITLE
Autosave form after change

### ISSUE THREAD

**Issue by joewestcott** [tannerlinsley/react-form#291]
First, thank you for this extremely useful library.

Is it possible to submit the form after a value change via the `<Form/>`'s onChange prop?
I know it's possible to get `formState` and `formApi` from it, but I've not worked out how to dispatch `formApi.submitForm()` without access to the `<form/>` node.

or, is this more of a [react issue](https://stackoverflow.com/questions/37901223/react-js-submit-form-programmatically-does-not-trigger-onsubmit-event/37902105)...?

**Comment by joepuzzo** [comment]
Technically you could just call formPi.submitForm in the onChange because it gives you access to the api

**Comment by joepuzzo** [comment]
Def anteresting use case tho .. typically you would not want to do somthing like this

**Comment by joewestcott** [comment]
> you could just call formPi.submitForm in the onChange

Would you be able to give an example of this? I've tried calling it with no arguments, and I don't think it's triggering all normal lifecycle events as described [here](https://react-form.js.org/#/).

> Def anteresting use case tho .. typically you would not want to do somthing like this

Any other ideas for solving the same issue? Thanks.

**Comment by joepuzzo** [comment]
Sorry i should have been more clear, so when I said

> Def an interesting use case tho .. typically you would not want to do somthing like this

What i meant is that forms are designed to be modified, and then finally when they are ready, submitted. Submission is a very well defined event and its designed to be the final step when a user is done modifying the form, not while they are actively modifying it. 

I guess this is why im a little confused as to why you need to call forms OnSubmit on every onChange. `onChange` was designed for your use case. It is a function that gets called every time the form updates. So you could do things like, save the state externally, or do other things whenever the form updates ( this sounds like your use case ). Not sure there is a point to calling onSubmit each time. If you were to, for example, interact with a firstName field in your form it would call all the lifecycle methods its supposed to and then callOnChange. Calling onSubmit would probably be overkill as it would call every fields lifecylcle method for no reason. If you really need updating one field to affect another then you can simply use a formLevel validator `<Form validate={someValidationFunction}`> and that validate function would get called on every onChange with all values.

**Comment by joewestcott** [comment]
Thanks for your reply.

>I guess this is why im a little confused as to why you need to call forms OnSubmit on every onChange. 

I could certainly call my own submit handler inside onChange (the function usually passed to `<Form/>`) but this library does a lot of nice things after a normal submit I'd have to replicate in onChange. So far, I'm making use of the `preSubmit` function, and `formApi.submitting` in a child component.

Unless I'm mistaken, I'd be required to replicate a lot of functionality, something like this: (untested)
````
const onChange = (mySubmitHandler) => (formState, formApi) => {
    // (will need to return here before the next line if values haven't changed)
    formApi.setFormState({ ...formState, submitting: true })
    mySubmitHandler(preSubmit(formState.values)).then(a => {
        formApi.setFormState({ ...formState, submitting: false, submitted: true })
    });
}

export default ({ mySubmitHandler }) => (
    <Form onChange={onChange(mySubmitHandler)} />
)
````

My desire to set `submitting` by the way, is because I have a component like this:

````
// previously wrapped with withFormApi...
const SaveIndicator = ({ formApi }) => (
    <span>{formApi.submitting ? "Saving" : "Saved"}<span>
)
````
(I should also mention `mySubmitHandler` is debounced, as the next thing it does is perform a network request)

Hopefully this gives you a good idea of the position I'm in!
