### ISSUE TITLE
Async validation called too aggressively

### ISSUE THREAD

**Issue by oliver-stripe** [tannerlinsley/react-form#292]
Docs for async validation at https://react-form.js.org/#/form-inputs say:

> The function will get called when you tab out of the field for the associated function.

However, it looks like it gets called `onChange` if synchronous validations pass. Is this intentional? What would be the suggested approach if we only wanted to async validate onBlur (or potentially debounce)? For example in a case where you make an XHR but don't want to fire a lot of requests.

**Comment by SirNerdBear** [comment]
I ran into this same problem. The asyncValidtor should only be called onBlur, as the documentation suggests.

Checking if a username is available (like the documentation shows as an example) is a prime example of too many API calls for every letter typed (not to mention errors being set when the user hasn't finished typing out what they want). 


If anyone sees a quick workaround I'd appreciate it.

**Comment by joepuzzo** [comment]
I actually agree with you guys. We updated it because some people actually want it to get called on every key stroke. What is cool however is that it does debounce for you. That being said maybe we should add a flag that allows you to turn off this feature and only call async validation on blur

**Comment by PumpedSardines** [comment]
Why was this closed, is there a way to only call validate on blur?
