### ISSUE TITLE
Add a new property "pristine" to formApi

### ISSUE THREAD

**Issue by JaffParker** [tannerlinsley/react-form#301]
I would like to propose an idea that is present in some other libraries and is fairly neat and shouldn't be that complicated.

formApi could have a property `pristine`, either a simple boolean or an object with info per field, that would show if the form values have been changed.

That could be useful, for example, if you want to disable the submit button until the form has been filled out.

Some might suggest that `touched` is a good alternative, however, it only shows if the field had focus, but not if anything was entered in it.

**Comment by joepuzzo** [comment]
Hey @JaffParker this is on radar and i have been wanting to add this for while. I wil leave this open until we get it in there.

**Comment by JaffParker** [comment]
Would be open for a PR? I could try to squeeze it in

**Comment by murphyke** [comment]
Is this what PR #319 is about?

**Comment by JaffParker** [comment]
@murphyke yes! It indeed is
