### ISSUE TITLE
React 16 Warning on defaultValue props

### ISSUE THREAD

**Issue by ragboyjr** [tannerlinsley/react-form#306]
If I set the `defaultValue` on the Field props, I get the error below. Since all of the form fields are controlled components, we probably should make sure to not pass the `defaultValue` prop down to the actual input field.

Warning: TextWrapper contains an input of type undefined with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components

**Comment by joshuaai** [comment]
I can confirm this problem. @ragboyjr a better approach might be to have an `initialValue` prop that you check against in the `select` value prop. That way we can set `initialValue` rather than `defaultValue` when using the library, and the warning will be suppressed. 

I can do a PR for this.

**Comment by orszaczky** [comment]
A possible workround is setting defaultValues on the Form itself:
<Form onSubmit={values => handleSubmit({values})} defaultValues={defaultValues}>

**Comment by ragboyjr** [comment]
I'm using a custom field, so I could avoid the warnings in the end.

**Comment by muntyanv** [comment]
+1

**Comment by Alex0007** [comment]
![image](https://user-images.githubusercontent.com/1143226/69893661-b25fb580-1336-11ea-853e-6c49fa1ec66c.png)

@tannerlinsley 
If defaultValue is not set, i see this warning. [Example](https://codesandbox.io/s/react-form-basic-form-with-inputfield-s3430) (name with defaultValue="", address without defaultValue)

After form submit address is not cleared with `instance.reset()`

```
    "react-form": "^4.0.1",
```
