### ISSUE TITLE
Default Checked Radio Button

### ISSUE THREAD

**Issue by Ogek** [tannerlinsley/react-form#310]
Hi guys,
how can I assign default value to the RadioGroup??

Thanks, bye

**Comment by cjkoepke** [comment]
I'm getting an issue with trying to implement this as well. Since the documentation doesn't give an example of how to do it, I've done my best to guess based on the code. The following, however, doesn't work:

```js
<RadioGroup field={field.key} value={field.value}>
    <fieldset className="field-switch__form--inline">
        {options && options.map((radio, index) => {
            return [
                <Radio
                    key={`${radio.value}-${index}-input`}
                    id={`${radio.value}-${index}-input`}
                    value={radio.value}
                    className="field-switch__form__input" />,
                <label
                    key={`${radio.value}-${index}-label`}
                    htmlFor={`${radio.value}-${index}-input`}>{radio.label}</label>
            ]
        })}
    </fieldset>
</RadioGroup>
```

Am I missing something? Thanks!

**Comment by jaandrews** [comment]
You can do this by setting the "defaultValue" property to the desired default on individual form elements (like RadioGroup or Checkbox). So you would have something like
``` jsx
<RadioGroup name="radioTest" defaultValue="Radio 1">
  <Radio id="radio-1" value="Radio 1"></Radio><label htmlFor="radio-1">Radio 1</label>
  <Radio id="radio-2" value="Radio 2"></Radio><label htmlFor="radio-2">Radio 2</label>
  <Radio id="radio-3" value="Radio 3"></Radio><label htmlFor="radio-3">Radio 3</label>
</RadioGroup>
```
You can also assign multiple properties at once on the Form element by passing in an (name, value) dictionary to the "defaultValues" prop (not to be confused with the html form element). See below for an example of this syntax
``` jsx
<Form defaultValues={{radioTest: 'Radio 1'}}>
  {formApi => (
    <form onSubmit={formApi.submitForm} id="form1" className="mb-4">
      <RadioGroup name="radioTest" defaultValue="Radio 1">
        <Radio id="radio-1" value="Radio 1"></Radio><label htmlFor="radio-1">Radio 1</label>
        <Radio id="radio-2" value="Radio 2"></Radio><label htmlFor="radio-2">Radio 2</label>
        <Radio id="radio-3" value="Radio 3"></Radio><label htmlFor="radio-3">Radio 3</label>
      </RadioGroup>
      <button type="submit" className="btn btn-primary">
        Submit
      </button>
    </form>
  )}
</Form>
```

The documentation isn't very clear on how to use these, so it took me a while to figure out how to use them too.

**Comment by joepuzzo** [comment]
@jaandrews is correct. You simply pass the value you want the radio set to. You can choose either method depending on your use case.

**Comment by Ogek** [comment]
Okok understood, just a question, what sense does it have to specify the default values ​​property to the Form component and repeat it also in the RadioGroup component? It's necessary?? I think no.
