### ISSUE TITLE
Form values are lost when using SSR and hydrate

### ISSUE THREAD

**Issue by Swatinem** [tannerlinsley/react-form#314]
This is a timing issue, the timeline looks a bit like this:

1. server renders a form using `ReactDOMServer.renderToString`
2. browser autofills the form
3. *at some later point*, react on the client kicks in via `ReactDOM.hydrate`
4. `onSubmit` will return empty form values, although the input fields do have values.

I have a PR coming up shortly with a proposed fix.

**Comment by Swatinem** [comment]
This is especially annoying when I want to build a login form with server side rendering and later hydration.
The browser auto-fills the credentials, but submitting the form right away gives me empty `values`.

**Comment by mjhm** [comment]
I'm not sure if this is related, but I'm observing the `preSubmit` function being executed after the form submission in my upgrade from 3.4.2 to 3.5.3.

**Comment by daviscabral** [comment]
It seems to be now fixed (#302) - but it's not passing the values resulted from `preSubmit`. Almost there - I'll try to hack something here to see if works.
