### ISSUE TITLE
Typescript error: `no exported member 'Field'`

### ISSUE THREAD

**Issue by bobek-balinek** [tannerlinsley/react-form#324]
Hi there, I'm trying to implement a custom form field element. Following the docs I've tried to import the `Field` component but encountered an error coming from Typescript:

`import { …, Field } from 'react-form';` 

`[ts] Module '"…/node_modules/@types/react-form/index"' has no exported member 'Field'.`

I've noticed in the changelog for the 3.0.0 that the field `FieldProps` has been renamed to `Field`. Perhaps the type definitions haven't been updated?

>The FormField component has been renamed to Field and is now a render-prop component which supports the "big three" render-prop formats (component and render/children functions).

**Comment by fruitraccoon** [comment]
Currently there are no typescript definitions for 3.x - there's another [open issue here (256)](https://github.com/react-tools/react-form/issues/256) if you're interested in the conversation.
