### ISSUE TITLE
Any idea how to reset form state?

### ISSUE THREAD

**Issue by thg303** [tannerlinsley/react-form#33]
Hi,
I have my form populated with "values", I could clear the form values by resetting the "values" but the touched state and errors are remaining there. any idea how to reset form state completely?

Render component like this:
```
<UserForm values={formUser}
                onSubmit={(values) => { ... }
                resetForm={(e) => {
                  e.preventDefault()
                  this.setState({formUser: null}, () => {
                    this.setState({formUser: {name: '', password:''})
                  })
                }}
              />
```

The form:
```
...
const UserFormComponent = ({values, submitForm, resetForm, setAllTouched}) => {

  return (
    <form onSubmit={submitForm}>
...
              <div>
                <button onClick={(e) => {
                  resetForm(e)
                  loadState(null)
                  setAllTouched(false)
                }}>RESET</button>
              </div>
              <div className="col-md-1">
                <button type="submit" >SUBMIT</button>
              </div>
    </form>
  )
}

const UserForm = Form({
  validate: validateUserForm
})(UserFormComponent)

export default UserForm

```

**Comment by tannerlinsley** [comment]
I'll add the API for this

**Comment by thg303** [comment]
Thanks. My current work around is to wrap the component in a flag variable and toggle it using `setState` method

**Comment by tizzle** [comment]
Hey,

i just wanted to share how i worked this out.

I always pass a defaultValues object to the form to control initial state. This object is present in the postSubmit lifecycle function of react-form. I then do something like this to clear the whole form after a submit:

```
postSubmit : (values, state, props ) => {
  Object.keys(props.defaultValues).map( ( key, index ) => {
    values[ key ] = props.defaultValues[key];
  });
}
```

This iterates over all keys in defaultValues and sets the values object to what it finds, resetting the form to it's initial state. Maybe you could use a variant of this as well to clear individual values.

**Comment by tannerlinsley** [comment]
I'm still working on this, and it's coming soon :)

**Comment by timothyallan** [comment]
Nice work Tanner, I just got the latest version and it seems to work great on initial tests :)
Reset buttons everywhere!

**Comment by tannerlinsley** [comment]
Awesome!  Close when you're satisfied :)

**Comment by timothyallan** [comment]
That's a job for @thg303 :)

**Comment by tannerlinsley** [comment]
Going out on a limb.... :)
