### ISSUE TITLE
If you don't take any issue in consideration please be fair and write it in the readme ...

### ISSUE THREAD

**Issue by BenNG** [tannerlinsley/react-form#337]
Like that people can choose an other project

**Comment by joepuzzo** [comment]
Hey sorry. I just built a new lib called informed as a replacement for this one and was going to update the readme this week.

**Comment by BenNG** [comment]
Well started months ago I can't change lib like that ... Why a complete rewrite instead of an progressive update ?

**Comment by joepuzzo** [comment]
This is no different than a Major version bump.. this was never fully my project. So i went and rewrote a version that u could personally support. The OG creator of react form and I talked it through and figured it would be best for me to take over the project.

**Comment by BenNG** [comment]
I see ... Is react-form will be deprecated ?

**Comment by joepuzzo** [comment]
React form is deprecated and we are now going to support informed https://www.npmjs.com/package/informed

**Comment by BenNG** [comment]
Got it ! Thx for answering my questions !
