### ISSUE TITLE
4.0.0-alpha.0 error with importing 'hooks/usePrevious'

### ISSUE THREAD

**Issue by BrianMitchL** [tannerlinsley/react-form#343]
I tried importing the alpha to play around with it but am getting a compile error:

`Module not found: Can't resolve 'hooks/usePrevious' in '/path-to-app/node_modules/react-form/dist'` coming from https://github.com/tannerlinsley/react-form/blob/60394c0eb0ee40922954320752989bdcefa5e3e7/src/index.js#L4

Was this envisioned to be an imported 3rd party hook?

**Comment by tannerlinsley** [comment]
Ah yeah. This is way out of date.

Tanner Linsley

**Comment by TeknoGuru** [comment]
![react-form](https://user-images.githubusercontent.com/51540055/64623532-682b0000-d3e9-11e9-80d8-90994f80b0bb.PNG)

"rollup v1.12.4
bundles src/index.js → dist\index.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
hooks/usePrevious (imported by src\index.js)
created dist\index.js in 2.8s

[2019-09-10 15:54:25] waiting for changes..."
i am new, nor sure what all this means but i have been waiting for the changes for close to 45 minutes now....it cant be an internet issue.

**Comment by tannerlinsley** [comment]
It's not. This library still needs to be updated to run and work on. Hang tight while I find time to do so.

**Comment by tannerlinsley** [comment]
This issue is now outdated
