### ISSUE TITLE
Add support of top level fields validation

### ISSUE THREAD

**Issue by nosovsh** [tannerlinsley/react-form#348]
Currently, `validation` option in `useForm` can set only top level errors. Will be nice if it would be possible to return an object with errors for each field, like 
```
useForm({
  validate: values => {
        const errors = {}
        if (!values.username) {
          errors.username = 'Required'
        }
        if (!values.password) {
          errors.password = 'Required'
        }
        return errors;
}}
```
it is usefull for huge forms where separate model validations are used like `yup` or swagger validation or whatever.

btw I really like api of this library

**Comment by tannerlinsley** [comment]
I'm currently working on a utility that will allow you to do this. It will look roughly like this:
```
useForm({
  validate: (values, instance) => {
        const errors = {}
        if (!values.username) {
          errors.username = 'Required'
        }
        if (!values.password) {
          errors.password = 'Required'
        }
        instance.setDeepMeta(errors)
        return undefined
}}
```

Technically you could do this on your own already by recursing over the `errors` object and using `instance.setFieldMeta('path.to.field', { error })`, but I realize that's a pain to roll on your own.

**Comment by tannerlinsley** [comment]
Until a really good pattern around this comes to light, I think I'm going to close this. Although it's possible, I don't really see it as the preferred method of validation for this library. Even a utility to do this would introduce a lot of edge cases around the API, including, but not limited to, how to clear errors and also how to provide different levels of field state including info/warning/success, etc. I've been down that road before with previous versions of this library and current versions of others and it usually doesn't end well. I'm happy to consider this conversation though for ongoing discussions. Change my mind :)
