### ISSUE TITLE
Using validation with v4.0.0-alpha.9 makes fields 'slow'

### ISSUE THREAD

**Issue by tm1000** [tannerlinsley/react-form#350]
When using v4.0.0-alpha.9 with validation the field responsiveness is much slower than without using validation. Even if the validation returns undefined. The only way around this is to use debouncing it appears

Faster
```
const validateNotEmpty = useCallback(
		(value, instance) =>
			instance.debounce(async () => {
				if (!value) {
					return 'This field can not be empty';
				}
				return false;
			}, 500),
		[]
	);
```

Lags
```
	const validateNotEmpty = useCallback((value, instance) => {
		if (!value) {
			return 'This field can not be empty';
		}
		return false;
	}, []);
```

**Comment by tm1000** [comment]
Additional Information. This appears only to be a major issue when React is in develop mode instead of production (in production It seems to be 'fast')

**Comment by tannerlinsley** [comment]
This is common for form libraries. Until we can get a codesandbox of really slow perf in production, going to close this for now.
