### ISSUE TITLE
Do not transpile async functions

### ISSUE THREAD

**Issue by nikku** [tannerlinsley/react-form#353]
Thanks for providing `react-form@4` :heart:.

I'm working with front-end requirements that would allow me to use async functions out of the box. Unfortunately I still need to bundle the regenerator runtime in order to use `react-form@4.0.0...`.

This leads me to the question if you could drop transpilation of async functions. 

At this point, all browsers except for IE 11 (dead) support async functions, cf. [caniuse](https://caniuse.com/#search=async). 

Using `babel@7` people that still need to support IE 11 or other (older) browsers could transpile `async` via overrides.

**Comment by timcosta** [comment]
I literally just ran into this same issue when compiling a Gatsby site after adding react-form:
```bash

  555 |   _asyncToGenerator(
  556 |   /*#__PURE__*/
> 557 |   regeneratorRuntime.mark(function _callee() {
      | ^
  558 |     var e,
  559 |         needsResubmit,
  560 |         fieldValidationPromises,


  WebpackError: ReferenceError: regeneratorRuntime is not defined

  - index.es.js:557 useForm
    node_modules/react-form/dist/index.es.js:557:1
```

Love the library, but this sneaky third party dep is causing some pain.

**Comment by tannerlinsley** [comment]
Yeah, let's do it. One of you wanna submit a PR for that?
