### ISSUE TITLE
Is there any possibility to give drag and drop in near future?

### ISSUE THREAD

**Issue by Nozibulla** [tannerlinsley/react-form#40]
Drag and drop option for bundle fields.

**Comment by SeeThruHead** [comment]
Drag and drop is fairly easy to implement with react-dnd and `swapValues` currently. Do you think we should supply a recipe for this?

**Comment by Nozibulla** [comment]
Yes please! that would be a great help.

**Comment by tannerlinsley** [comment]
If anyone would like to produce a recipe or example for how to do this, I will gladly post it to the wiki. Closing this issue for now.
