### ISSUE TITLE
Manually submit form outside of <Form> component

### ISSUE THREAD

**Issue by TimMikeladze** [tannerlinsley/react-form#42]
It would be useful to call the submit and validate methods of a form while in a different component outside of the <Form> parent. Consider the scenario when you want to have your submit form button reside in a different component hierarchy then the form. 

Maybe it's already possible to do this? 

Please let me know what you think, thanks.

**Comment by tannerlinsley** [comment]
The easiest way to do this is to use a ref:
```javascript
<ReactForm ref={el => this.form = el}>

// Somewhere else in the parent component
this.form.submitForm()
```

Does that work for you?

**Comment by TimMikeladze** [comment]
Thank you for the response!

**Comment by z-vr** [comment]
Thanks, wouldn't know what to do otherwise. @tannerlinsley I think it would be worth adding to the documentation.

**Comment by tannerlinsley** [comment]
Yeah I plan on it

**Comment by z-vr** [comment]
@tannerlinsley  this has stopped working in `v2`, `submitForm` is not a function which I can access after creating a `ref` to the form. Any idea why?
