### ISSUE TITLE
Should we have setValues method?

### ISSUE THREAD

**Issue by hnq90** [tannerlinsley/react-form#49]
If we want to set value to multiple fields at once, we have to use `setValues`.

Example:
```
setValue('field1', value1)
setValue('field2', value1)
setValue('field3', value1)
setValue('field4', value1)
...
setValue('field99', value1)
```

Use `setAllValues` will set/replace all form values but it makes other attributes which are not in `setAllValues` arguments is undefined.

We can create an object which merges values from form's value with new values as:
```
<Form>
  {({values, setAllValues}) => {
    const profile = {
      name: 'Tanner Linsley',
      job: 'Software Developer',
      age: 27
    }
   const newValues = Object.assign({}, values, profile)
    return (
      <button onClick={() => setAllValues(newValues)}
  }}
</Form>
```

IMHO, it's better to have a new method `setValues` or `setMultipleValues` which doesn't override others fields' value.

Please let me know your opinion.

**Comment by SeeThruHead** [comment]
Please correct me if I'm wrong but if you always have `values` passed down when you get `setAllValues` can this not be implemented 100% in userland? ie by wrapping setValues

**Comment by tannerlinsley** [comment]
Just call serAllValues using the spread operator with the existing values
followed by any new values.

**Comment by hnq90** [comment]
Thanks, that's which I used.
