### ISSUE TITLE
React.createClass and React.PropTypes are deprecated

### ISSUE THREAD

**Issue by thchia** [tannerlinsley/react-form#54]
In React 15.5.0, createClass and PropTypes are deprecated.

https://github.com/facebook/react/blob/master/CHANGELOG.md#1550-april-7-2017

PropTypes should now come from 
https://www.npmjs.com/package/prop-types

**Comment by abhimanyu1289** [comment]
Looks like this is part of v1.2.6. 
But I am still getting warnings for createClass and PropTypes.

**Comment by thchia** [comment]
I believe 1.2.6 is still using createClass and React.propTypes. It's been mentioned that the next version will handle the deprecations.

**Comment by danielo515** [comment]
1.2.6 is indeed using prototypes . Please release 1.2.7 so we can get rid of this messages
