### ISSUE TITLE
Checkbox component does not handle getValue properly

### ISSUE THREAD

**Issue by joshuamanns** [tannerlinsley/react-form#56]
I'm unable to create a controlled checkbox using any approach....
Setting the `checked` property does nothing.
Setting the `value` property does nothing.
Setting `defaultChecked` conflicts with controlled/uncontrolled react requirements.

The only solution I've found is modifying the source so that line 47: `checked: getValue(false),` is changed to `checked: getValue(),` and managing the Checkbox's `checked` prop with state and an onChange handler.

**Comment by joshuamanns** [comment]
@tannerlinsley I'm getting mixed results here. If I double click the checkbox it will sometimes toggle, but otherwise it does not function... Could you please advise on why this is not behaving as expected? Are there known compatibility issues with other libraries/dependencies? It appears to only happen within the context of my project, even when copy/pasting your storybook code verbatim.

**Comment by tannerlinsley** [comment]
I will take a look at this tomorrow morning as I run through issues :)

**Comment by joshuamanns** [comment]
@tannerlinsley After some cursory glances, it looks like your library might take issue with Fastclick's synthetic events. It's strange, because this shouldn't be an issue on Desktop where I'm experiencing the problem. Do you have any insight here?

**Comment by bruceharris** [comment]
@joshuamanns @tannerlinsley I'm experiencing similar trouble; any update on this issue? thanks

**Comment by tannerlinsley** [comment]
I've added fast click to the documentation and it seems to be working just fine :)
