### ISSUE TITLE
Wrong example for onSubmit in README

### ISSUE THREAD

**Issue by justrag** [tannerlinsley/react-form#6]
onSubmit example in README is a copy of preSubmit example
https://github.com/tannerlinsley/react-form?#onsubmit-values-state-props

**Comment by tannerlinsley** [comment]
Nice catch!  If you want to fix it I'll accept a PR. Otherwise I'll fix that as soon as I can

**Comment by tannerlinsley** [comment]
Fixed in a12dd57ca67d9b1e4c7e14299f7be16893bacadc
