### ISSUE TITLE
How to set the Select default value

### ISSUE THREAD

**Issue by danielo515** [tannerlinsley/react-form#61]
Hello,

I want to know how to set the default selected value of one `Select` component. There is no mention on the docs.

Thanks

**Comment by tannerlinsley** [comment]
This is done by providing an option in your options array that matches the inputs key from your `defaultValues` prop:
```javascript

<Form defaultValues={{ person: 'bob' }}>
...
<Select field='person' options={[{
label: 'Bob',
value: 'bob'
}]} />
```

Notice how `person: 'bob'` in defaultValues will match up to the option with `value: 'bob'` :)

**Comment by mihaiblaga89** [comment]
Setting the default value prohibits the select change. 

`defaultValues={{
	inUS: 0
}}`

`
<Select
	onChange={(e, onChange) => {
		const { value } = e.target;
		self.setState({ residingInUS: value === '1' ? true : false });
		onChange();
	}}
	field="inUS"
	options={[{
		key: 1,
		label: 'Yes',
		value: true
	}, {
		key: 2,
		label: 'No',
		value: false
	}]}
/>`

The onChange is triggered with the correct value, but the value in the select does not change.
