### ISSUE TITLE
Select options should have explicit value attribute

### ISSUE THREAD

**Issue by thomas-p-wilson** [tannerlinsley/react-form#67]
Given the following options:

```
const options = [{
  'label': 'A',
  'value': 'a'
}, {
  'label': 'B',
  'value': 'b'
}]
```

The resulting Select would look something like:

```
<select>
  <option value="0">A</option>
  <option value="1">B</option>
</select>
```

Whereas the expected and proper result looks like:

```
<select>
  <option value="a">A</option>
  <option value="b">B</option>
</select>
```

It's a very minimal alteration for which I already have a branch, and will PR momentarily.

**Comment by tannerlinsley** [comment]
This will break support for complex values like objects and non-primitives.

**Comment by thomas-p-wilson** [comment]
So make it optional then?
