### ISSUE TITLE
How to add class in your components?

### ISSUE THREAD

**Issue by dns2316** [tannerlinsley/react-form#70]
Example, I want add bootstrap class to Textarea

                    <Textarea
                      id="body-form"
                      field='body'
                      placeholder='bodyForm'
                     />

was id added, but how to add class?

P.S: and how to set url database, and how to POST, Update, Delete from DB?

**Comment by tannerlinsley** [comment]
- Use the `className` prop to set a class on the TextArea.
- React-Form is not responsible for communicating with API's or databases on its own. You could join the slack channel and ask for help though :)
