### ISSUE TITLE
Returns the undefined question under this.props.form.getFieldsValue ()

### ISSUE THREAD

**Issue by LikeYakult** [tannerlinsley/react-form#76]
### 1. Version：
antd , 2.10.2
### 2. Environment：
Chrome 58 , window 10
### 3.What did you do?
Use this.props.form.getFieldsValue () to take the value in the form
### 4.The code is as follows:
```
import React, { Component } from 'react';
import { Form, Input, Button } from 'antd';
const FormItem = Form.Item;
lass Demo extends Component{
    handleSubmit = (e) => {
        // 阻止事件冒泡
        e.preventDefault();
        var formData = this.props.form.getFieldsValue();
        console.log(formData);
    };
    render()  {
        const { getFieldDecorator } = this.props.form;
        return (
            <Form layout="horizontal" onSubmit={this.handleSubmit}>
                <FormItem label="Account">
                    <Input placeholder="please input the account"
                        {...getFieldDecorator('userName')}/>
                </FormItem>
                <FormItem label="Password">
                    <Input type="password" placeholder="Please input the pasword"
                        {...getFieldDecorator('passWord')}/>
                </FormItem>
                <Button type="primary" htmlType="submit">Submit</Button>
            </Form>
        );
    }
}
export default Demo = Form.create()(Demo);
```
### 5.The result you expect is:
Use this.props.form.getFieldsValue () to take the value in the form
### 6.The actual result is:
![qq 20170530182002](https://cloud.githubusercontent.com/assets/22496926/26579048/da026f26-4564-11e7-8eea-fe58fca2aa26.png)

**Comment by ummahusla** [comment]
I assume you copy and pasted incorrectly `lass Demo extends Component{`

**Comment by tannerlinsley** [comment]
I'm not familiar with the `getFieldsValue` method.  This is not a part of the current api.

**Comment by tannerlinsley** [comment]
From the look of it, I believe you are referring to the wrong react form library :( Closing for now

**Comment by LikeYakult** [comment]
@ummahusla Oh, yes, thanks for it

**Comment by LikeYakult** [comment]
@tannerlinsley Yes, I am learning based on the old version of the api, the old version of the tutorial to get the value of the form, I use the latest version to write but get to the undefined, which makes me very confused
