### ISSUE TITLE
Error classes

### ISSUE THREAD

**Issue by nerdstep** [tannerlinsley/react-form#77]
Any thoughts on an option to override the default error class name? It would also be nice to be able to provide a custom class name to FormError. I'm using custom inputs to achieve this now, but it seems like a lot of extra ceremony.

**Comment by tannerlinsley** [comment]
Use the `errorProps` prop on any form input to forward props to the underlying FormError component. Ex: 
```javascript
<Text // This is the built-in Text formInput, but could be any FormInput component
  field="name"
  errorProps={{
    style: {
      background: 'blue'
    },
    className: 'customFormError'
  }}
/>
```

**Comment by nerdstep** [comment]
Ah, excellent! Sorry, missed that one in the docs!
