### ISSUE TITLE
Updating default values

### ISSUE THREAD

**Issue by z-vr** [tannerlinsley/react-form#78]
If a form has not been changed and all values stayed default, then `deafultValues` of the form has changed -- shall the values in the form be updated to new defaults? If I do `resetForm`, all values will be reset to default, whereas I only want fields containing previous defaults to be updated to new ones. 

Thanks.

**Comment by vladra** [comment]
I've noticed same bug today also.

It seems it was introduced recently, cause I think reset form was working fine for me some time ago.

Basically when user updates form values, `defaultValues` property of the form updated also. This breaks `resetForm` function, being unable to set initial form values

**Comment by z-vr** [comment]
@vladra this is not I meant. I want to update `deafultValues` in render() and see new defaults in those fields which have not been touched.

**Comment by mgutz** [comment]
I made a fix in our fork

https://github.com/matcherino/react-form/blob/update-default-values/src/form.js#L75

Need to test it more before submitting a P

**Comment by tannerlinsley** [comment]
Should be fixed in latest version
