### ISSUE TITLE
Is it possible to make the resetForm NOT refresh the page?

### ISSUE THREAD

**Issue by jamesone** [tannerlinsley/react-form#79]
Instead can we make it just clear the form values without a page refresh?

**Comment by tannerlinsley** [comment]
The page does not refresh when you reset a form with `instance.resetForm()`.  If you are experience this problem it likely has to do with the way you are calling that method. Make sure you are using `event.preventDefault()` on form events, else it will reload the page as it would in a standard HTML5 environemtn
