### ISSUE TITLE
radio buttons ? 

### ISSUE THREAD

**Issue by VasilyShelkov** [tannerlinsley/react-form#8]
Are there any plans to handle radio buttons?

How would you suggest handling them ?

**Comment by tannerlinsley** [comment]
Radios would be fairly straight forward to handle. The question always
lands on whether to generate the options from an array or make the user
generate the options with a smaller building block. I personally want to
implement the latter, but was waiting for some feedback first

**Comment by tannerlinsley** [comment]
Fixed in 5eadda7422ffb510da4e64be8b22544713cfe90f :)

**Comment by tannerlinsley** [comment]
https://github.com/tannerlinsley/react-form#-text-select-checkbox-textarea-radio-

**Comment by VasilyShelkov** [comment]
Rapid turn around thanks :D

I don't think I minded either way but personally would have thought as radio buttons as separate entities so made sense with the latter and kinda stays consistent with the format or checkboxes which I think they're most similar to. 

👍

**Comment by tannerlinsley** [comment]
Awesome! Good to hear
