### ISSUE TITLE
getInitialState on ES6 Components

### ISSUE THREAD

**Issue by jandramila** [tannerlinsley/react-form#81]
So, I'm currently using [warning](https://github.com/BerkeleyTrue/warning) and whenever i mount React Form i get this message:

![Logged Warning](https://user-images.githubusercontent.com/10802091/27883101-b83413e2-61a5-11e7-8ae8-7d1cb4a29905.png)

Are you guys aware of this? Apparently this library warns about getInitialState being used in a JS class, so we should set this.state on the constructor.

I can make a PR of this if has not been attacked. Thanks.

**Comment by tannerlinsley** [comment]
I would love a PR to clean this up.  Technically the state should now be defined in the `constructor` as far as I'm aware.

**Comment by jandramila** [comment]
No problem at all, i'll put my hands on it by this weekend.

**Comment by tannerlinsley** [comment]
Hey, I'm working on this right now, so take a rain check on this for now ;)

**Comment by tannerlinsley** [comment]
Fixed in next release
