### ISSUE TITLE
Question: can style of field validation be set?

### ISSUE THREAD

**Issue by keiranmraine** [tannerlinsley/react-form#82]
Hi,

Is it possible to set the text colour for the field validation 'help' text?

E.g.  I'd like to set the text colour following the field to red:

<img width="253" alt="screen shot 2017-07-06 at 18 34 38" src="https://user-images.githubusercontent.com/3740323/27924640-e1393982-6279-11e7-90ef-6410546bafb1.png">

Thanks

**Comment by tannerlinsley** [comment]
Use the `errorProps` prop on any form input to forward props to the underlying FormError component. Ex: 
```javascript
<Text // This is the built-in Text formInput, but could be any FormInput component
  field="name"
  errorProps={{
    style: {
      background: 'blue'
    },
    className: 'customFormError'
  }}
/>
```
