### ISSUE TITLE
Dirty is not actually being exposed on the API

### ISSUE THREAD

**Issue by joepuzzo** [tannerlinsley/react-form#85]
Could have something to do with the setValue function in `form.js`. But i'm noticing that as i type, the touched value is not getting updated until I tab out of a field.

**Comment by joepuzzo** [comment]
Ok maybe my understanding of touched was incorrect. Is there any way to detect when a field is dirty? i.e has been entered/interacted with?

**Comment by joepuzzo** [comment]
Looks like dirty is not getting exposed on the "api".

**Comment by tannerlinsley** [comment]
I believe you were looking for `getTouched`?
